name: CI

on: [push]

jobs:
  build:
    name: Test that the sass compiles
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - run: npm test
    env:
      CI: true
